name: Build and Upload Android Release

on:
  pull_request:
    branches: [ "master" ]
    tags:
      - "v*"
  push:
    branches: [ "master" ]
    tags:
      - "v*"

jobs:
  build-and-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Load Google Service files and Decode
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > /home/runner/work/ShutterShop/ShutterShop/app/google-services.json
      - name: Decode Keystore from Github Secrets
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $ENCODED_STRING | base64 -di > /home/runner/work/ShutterShop/ShutterShop/keystore.jks
      - name: Build Release apk
        env:
          SIGNING_PATH: /home/runner/work/ShutterShop/ShutterShop/keystore.jks
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: ./gradlew assembleRelease
      - name: Generate Release Tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.API_KEY_CI_CD }}
          tag_prefix: 'v'
          tag_template: 'yyyy.mm.dd.i'
      - name: Create Release Application
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          token: ${{secrets.API_KEY_CI_CD}}
          generate_release_notes: true
          files: |
            app/release/app-release.apk
