name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
      delete_workflow_pattern:
        description: 'Name or filename of the workflow (if not set, all workflows are targeted)'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2.0.6  
      with:
        token: ${{ secrets.API_KEY_CI_CD }}
        delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
